### ISSUE TITLE
Disable Up and Down transition animations

### ISSUE THREAD

**Issue by Alexookah** [blueimp/Gallery#242]
Hi I am using this great library, and would like to know if there is a way to disable the up and down transition animations. In order to have only left and right slide gestures to change slides. Is there some option in initialisation that i missed?

**Comment by blueimp** [comment]
Hi @Alexookah,

if you just wanna disable closing the lightbox on swipe up/down, you can set the [option](https://github.com/blueimp/Gallery#default-options) `closeOnSwipeUpOrDown` to `false`.

If you want the browser default behavior when swiping up/down, you can set the following CSS styles:

```css
.blueimp-gallery {
    -ms-touch-action: pan-y pinch-zoom;
    touch-action: pan-y pinch-zoom;
}
```

Hope that helps! Please also provide a description of your use case. ☺️
